[project]
name = "usenet_no"
version = "0.1.0"
description = "Explore norwegian usenet data from internet archive"
authors = [
    {name = "Tita", email = "tita.enstad@nb.no"},
]
dependencies = ["ipykernel>=6.29.5", "requests>=2.32.3", "beautifulsoup4>=4.12.3", "tqdm>=4.67.0"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true
